id: P000468
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W27311
  title: བོད་ཀྱི་ཆོས་སྲིད་ཟུང་འབྲེལ་སྐོར་བཤད་པ
  author: ''
  volumes:
    276ba5f0ab094f298cb2ad2eb9d04480:
      image_group_id: I4312
      title: ''
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
